### ISSUE TITLE
hashtopolis Agent on Mac OS X Issue (missing hashcat64.osx)

### ISSUE THREAD

**Issue by apostolovd** [s3inlc/hashtopolis-agent#38]
Hi Team,
While I was testing the hashtopolis (CSharp / mono) i end up in a small issue (not big deal at all) and it is occurring while using a mac os x (10.12.6) as a client.
The hashtopolis agent is working fine but whenever is doing the cracker check and installation it is looking for .osx as defined in Util.class.php which leads to the following error:

```
Downloading from http://*/getHashlist.php?hashlists=*&token=*
Downloading 100% @ 9.34 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"*","binaryVersionId":*,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.1.0.7z","name":"hashcat","executable":"hashcat.osx"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"*","taskId":*}
{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Could not locate /*/hashtopolis/hashcat/4/hashcat64.osx
Keyspace measuring was unsuccessful, check all files are present
Getting task
```

Of course once you rename and move your complied hashcat in the request folder it is working great :)
```
Downloading from http://*/getHashlist.php?hashlists=*&token=*
Downloading 100% @ 0.29 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"*","binaryVersionId":*,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.1.0.7z","name":"hashcat","executable":"hashcat.osx"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"*","taskId":*}
{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /*/hashtopolis/hashcat/4 as working directory
```

Im not sure if i have to submit it as an issue so if u think it is not...just remove it :)

Thanks for the great solution!!!

**Comment by s3inlc** [comment]
That's just a special case on OS X, as the prebuilt hashcat downloads do not contain OS X binaries. So you either have to put the binaries at their place on the agents manually (as you did), or the more convenient solution is to just pack the hashcat64.osx binary into the hashcat 7z and then make it available for download on the hashtopolis server and use this as the source for the cracker. This would be less work, especially when you have more than one agent (where the manual thing would be much more work to do).

So a better solution would be better of course, but as you have to build the OS X binaries yourself because they are not provided directly from hashcat, there currently is not a better way.

**Comment by apostolovd** [comment]
Hi s3inlc,
Thanks for the quick response. :) I'm not going to further distribute it to any macosx(i dont any other unfortunately) so i just shared it for the rest of world as there might be people struggling to get it working.

Meanwhile i just tested to run with OpenCL and it is working great. Thanks once again for the great product..just love it
